### ISSUE TITLE
Error when using custom reference data

### ISSUE THREAD

**Issue by heesuallykim** [atgu/GWASpy#2]
I am getting the following error when using my own reference data:

AttributeError: StructExpression instance has no field, method, or property 'Project'

**Comment by LindoNkambule** [comment]
GWASpy assumes the `ref_info` TSV file has a column named `Project` (used in plotting PCA results). This is how the default `ref_info` file looks like:
| Sample | SuperPop | Project |
| --------- | --------- | --------- | 
| HG00096 | EUR | 1KG |
| ... | ... | ... |
| SS6004476 | AMR | HGDP |

I will update the docs
